# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-hooks.json
- id: dotnet-format
  name: Format dotnet files
  description: Run the "dotnet format" command, fixing any issues.
  entry: dotnet format
  language: system
  types:
    - c#
- id: dotnet-lint
  name: Lint dotnet files
  description: Run the "dotnet format" command, verifying there would be no changes made.
  entry: dotnet format --verify-no-changes
  language: system
  types:
    - c#
- id: pnpm-lint
  name: Run pnpm lint
  description: Run the pnpm lint script.
  entry: pnpm run lint
  language: system
  types:
    - ts
    - javascript
- id: pnpm-lint-recurse
  name: Run pnpm lint (recurse)
  description: Run the pnpm lint script recursively.
  entry: pnpm -r run lint
  language: system
  types:
    - ts
    - javascript
- id: pnpm-test
  name: Run pnpm test
  description: Run the pnpm test script.
  entry: pnpm run test
  language: system
  pass_filenames: false
- id: pnpm-test-recurse
  name: Run pnpm test (recurse)
  description: Run the pnpm test script recursively.
  entry: pnpm -r run test
  language: system
  pass_filenames: false
