# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-hooks.json
- id: dotnet-format
  name: Format dotnet files
  description: Run the "dotnet format" command, fixing any issues.
  entry: dotnet format
  language: system
  types:
      - c#
  pass_filenames: false
- id: dotnet-lint
  name: Lint dotnet files
  description: Run the "dotnet format" command, verifying there would be no changes made.
  entry: dotnet format --verify-no-changes
  language: system
  types:
      - c#
  pass_filenames: false
- id: pnpm-lint
  name: Run pnpm lint
  description: Run the pnpm lint script.
  entry: pnpm run lint
  language: system
  types_or:
      - ts
      - javascript
- id: pnpm-lint-ci
  name: Run pnpm lint:ci
  description: Run the pnpm lint:ci script.
  entry: pnpm run lint:ci
  language: system
  types_or:
      - ts
      - javascript
- id: pnpm-lint-recurse
  name: Run pnpm lint (recurse)
  description: Run the pnpm lint script recursively.
  entry: pnpm -r run lint
  language: system
  types_or:
      - ts
      - javascript
  pass_filenames: false
- id: pnpm-lint-ci-recurse
  name: Run pnpm lint:ci (recurse)
  description: Run the pnpm lint:ci script recursively.
  entry: pnpm -r run lint:ci
  language: system
  types_or:
      - ts
      - javascript
  pass_filenames: false
- id: pnpm-test
  name: Run pnpm test
  description: Run the pnpm test script.
  entry: pnpm run test
  language: system
  types_or:
      - ts
      - javascript
  pass_filenames: false
- id: pnpm-test-ci
  name: Run pnpm test:ci
  description: Run the pnpm test:ci script.
  entry: pnpm run test:ci
  language: system
  types_or:
      - ts
      - javascript
  pass_filenames: false
- id: pnpm-test-recurse
  name: Run pnpm test (recurse)
  description: Run the pnpm test script recursively.
  entry: pnpm -r run test
  language: system
  types_or:
      - ts
      - javascript
  pass_filenames: false
- id: pnpm-test-ci-recurse
  name: Run pnpm test:ci (recurse)
  description: Run the pnpm test:ci script recursively.
  entry: pnpm -r run test:ci
  language: system
  types_or:
      - ts
      - javascript
  pass_filenames: false
- id: odin-lint-makefile
  name: Lint Odin (Makefile)
  description: Lint an Odin project using a Makefile.
  entry: make lint
  language: system
  types:
      - file
  files: \.(odin)$
  pass_filenames: false
- id: deno-lint
  name: Lint Deno
  description: Lint a Deno project.
  entry: deno lint
  language: system
  types:
      - ts
- id: deno-lint-fix
  name: Lint Deno (Fix)
  description: Lint a Deno project and fix any issues found.
  entry: deno lint --fix
  language: system
  types:
      - ts
- id: clang-format-cpp
  name: clang-format (C/C++)
  description: Run clang-format on C/C++ files.
  entry: clang-format --dry-run
  language: system
  types:
      - c
      - c++
- id: clang-format-objc
  name: clang-format (Objective-C)
  description: Run clang-format on Objective-C files.
  entry: clang-format --dry-run
  language: system
  types:
      - objective-c
      - objective-c++
- id: clang-format-java
  name: clang-format (Java)
  description: Run clang-format on Java files.
  entry: clang-format --dry-run
  language: system
  types:
      - java
- id: clang-format-javascript
  name: clang-format (JavaScript)
  description: Run clang-format on JavaScript files.
  entry: clang-format --dry-run
  language: system
  types:
      - javascript
- id: clang-format-csharp
  name: clang-format (C#)
  description: Run clang-format on C# files.
  entry: clang-format --dry-run
  language: system
  types:
      - c#
- id: clang-format-cpp-strict
  name: clang-format (C/C++) (Strict)
  description: Run clang-format on C/C++ files and treat all warnings as errors.
  entry: clang-format --dry-run --Werror
  language: system
  types:
      - c
      - c++
- id: clang-format-objc-strict
  name: clang-format (Objective-C) (Strict)
  description: Run clang-format on Objective-C files  and treat all warnings as errors.
  entry: clang-format --dry-run --Werror
  language: system
  types:
      - objective-c
      - objective-c++
- id: clang-format-java-strict
  name: clang-format (Java) (Strict)
  description: Run clang-format on Java files  and treat all warnings as errors.
  entry: clang-format --dry-run --Werror
  language: system
  types:
      - java
- id: clang-format-javascript-strict
  name: clang-format (JavaScript) (Strict)
  description: Run clang-format on JavaScript files  and treat all warnings as errors.
  entry: clang-format --dry-run --Werror
  language: system
  types:
      - javascript
- id: clang-format-csharp-strict
  name: clang-format (C#) (Strict)
  description: Run clang-format on C# files  and treat all warnings as errors.
  entry: clang-format --dry-run --Werror
  language: system
  types:
      - c#
- id: clang-format-cpp-fix
  name: clang-format (C/C++) (Fix)
  description: Run clang-format on C/C++ files and fix any issues found.
  entry: clang-format -i
  language: system
  types:
      - c
      - c++
- id: clang-format-objc-fix
  name: clang-format (Objective-C) (Fix)
  description: Run clang-format on Objective-C files and fix any issues found.
  entry: clang-format -i
  language: system
  types:
      - objective-c
      - objective-c++
- id: clang-format-java-fix
  name: clang-format (Java) (Fix)
  description: Run clang-format on Java files and fix any issues found.
  entry: clang-format -i
  language: system
  types:
      - java
- id: clang-format-javascript-fix
  name: clang-format (JavaScript) (Fix)
  description: Run clang-format on JavaScript files and fix any issues found.
  entry: clang-format -i
  language: system
  types:
      - javascript
- id: clang-format-csharp-fix
  name: clang-format (C#) (Fix)
  description: Run clang-format on C# files and fix any issues found.
  entry: clang-format -i
  language: system
  types:
      - c#
- id: gradle-spotless
  name: Gradle (Spotless)
  description: Run Spotless via Gradle on Java files.
  entry: gradle spotlessJavaCheck
  language: system
  types:
      - java
  pass_filenames: false
- id: gradle-spotless-fix
  name: Gradle (Spotless) (Fix)
  description: Run Spotless via Gradle on Java files and fix any issues found.
  entry: gradle spotlessJavaApply
  language: system
  types:
      - java
  pass_filenames: false
- id: gradlew-spotless
  name: Gradle (Spotless)
  description: Run Spotless via Gradle on Java files.
  entry: bash -c "[[ -z \\"$(uname -a | grep -i wsl)\\" ]] && ./gradlew spotlessJavaCheck || cmd.exe /Q /C .\\\\gradlew.bat spotlessJavaCheck"
  language: system
  types:
      - java
  pass_filenames: false
- id: gradlew-spotless-fix
  name: Gradle (Spotless) (Fix)
  description: Run Spotless via Gradle on Java files and fix any issues found.
  entry: bash -c "[[ -z \\"$(uname -a | grep -i wsl)\\" ]] && ./gradlew spotlessJavaApply || cmd.exe /Q /C .\\\\gradlew.bat spotlessJavaApply"
  language: system
  types:
      - java
  pass_filenames: false
