# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-hooks.json
- id: dotnet-format
  name: Format dotnet files
  description: Run the "dotnet format" command, fixing any issues.
  entry: dotnet format
  language: system
  types:
    - c#
  pass_filenames: false
- id: dotnet-lint
  name: Lint dotnet files
  description: Run the "dotnet format" command, verifying there would be no changes made.
  entry: dotnet format --verify-no-changes
  language: system
  types:
    - c#
- id: dotnet-test
  name: Test dotnet
  description: Run the "dotnet test" command.
  entry: dotnet test
  language: system
  types:
    - c#
  pass_filenames: false
- id: dotnet-test-coverage
  name: Test dotnet (Code Coverage)
  description: Run the "dotnet test" command, with code coverage output.
  entry: dotnet test --collect "Code Coverage"
  language: system
  types:
    - c#
  pass_filenames: false
- id: dotnet-test-coverage-xplat
  name: Test dotnet (XPlat Code Coverage)
  description: Run the "dotnet test" command, with cross-platform code coverage output.
  entry: dotnet test --collect "XPlat Code Coverage"
  language: system
  types:
    - c#
  pass_filenames: false
- id: pnpm-lint
  name: Run pnpm lint
  description: Run the pnpm lint script.
  entry: pnpm run lint
  language: system
  types_or:
    - ts
    - javascript
- id: pnpm-lint-ci
  name: Run pnpm lint:ci
  description: Run the pnpm lint:ci script.
  entry: pnpm run lint:ci
  language: system
  types_or:
    - ts
    - javascript
- id: pnpm-lint-recurse
  name: Run pnpm lint (recurse)
  description: Run the pnpm lint script recursively.
  entry: pnpm -r run lint
  language: system
  types_or:
    - ts
    - javascript
  pass_filenames: false
- id: pnpm-lint-ci-recurse
  name: Run pnpm lint:ci (recurse)
  description: Run the pnpm lint:ci script recursively.
  entry: pnpm -r run lint:ci
  language: system
  types_or:
    - ts
    - javascript
  pass_filenames: false
- id: pnpm-test
  name: Run pnpm test
  description: Run the pnpm test script.
  entry: pnpm run test
  language: system
  types_or:
    - ts
    - javascript
  pass_filenames: false
- id: pnpm-test-ci
  name: Run pnpm test:ci
  description: Run the pnpm test:ci script.
  entry: pnpm run test:ci
  language: system
  types_or:
    - ts
    - javascript
  pass_filenames: false
- id: pnpm-test-recurse
  name: Run pnpm test (recurse)
  description: Run the pnpm test script recursively.
  entry: pnpm -r run test
  language: system
  types_or:
    - ts
    - javascript
  pass_filenames: false
- id: pnpm-test-ci-recurse
  name: Run pnpm test:ci (recurse)
  description: Run the pnpm test:ci script recursively.
  entry: pnpm -r run test:ci
  language: system
  types_or:
    - ts
    - javascript
  pass_filenames: false
- id: odin-lint-makefile
  name: Lint Odin (Makefile)
  description: Lint an Odin project using a Makefile.
  entry: make lint
  language: system
  types:
    - file
  files: \.(odin)$
  pass_filenames: false
- id: deno-test
  name: Test Deno
  description: Test a Deno project.
  entry: deno test
  language: system
  types:
    - ts
- id: deno-lint
  name: Lint Deno
  description: Lint a Deno project.
  entry: deno lint
  language: system
  types:
    - ts
- id: deno-lint-fix
  name: Lint Deno (Fix)
  description: Lint a Deno project and fix any issues found.
  entry: deno lint --fix
  language: system
  types:
    - ts
- id: deno-task-test
  name: Deno Run Task (Test)
  description: Run the "test" task on a Deno project.
  entry: deno task
  args:
    - test
  language: system
  types:
    - ts
  pass_filenames: false
- id: deno-task-test-coverage
  name: Deno Run Task (Test with Coverage)
  description: Run the "test:coverage" task on a Deno project.
  entry: deno task
  args:
    - test:coverage
  language: system
  types:
    - ts
  pass_filenames: false
- id: deno-task-recursive-test
  name: Deno Run Task Recursively (Test)
  description: Run the "test" task recursively on a Deno workspace.
  entry: deno task --recursive
  args:
    - test
  language: system
  types:
    - ts
  pass_filenames: false
- id: deno-task-recursive-test-coverage
  name: Deno Run Task Recursively (Test with Coverage)
  description: Run the "test:coverage" task recursively on a Deno workspace.
  entry: deno task --recursive
  args:
    - test:coverage
  language: system
  types:
    - ts
  pass_filenames: false
- id: deno-task-lint
  name: Deno Run Task (Lint)
  description: Run the "lint" task on a Deno project.
  entry: deno task
  args:
    - lint
  language: system
  types:
    - ts
- id: deno-task-lint-fix
  name: Deno Run Task (Lint and Fix)
  description: Run the "lint:fix" task on a Deno project and fix linting issues found.
  entry: deno task
  args:
    - lint:fix
  language: system
  types:
    - ts
- id: deno-task-recursive-lint
  name: Deno Run Task Recursively (Lint)
  description: Run the "lint" task recursively on a Deno workspace.
  entry: deno task --recursive
  args:
    - lint
  language: system
  types:
    - ts
  pass_filenames: false
- id: deno-task-recursive-lint-fix
  name: Deno Run Task Recursively (Lint and Fix)
  description: Run the "lint:fix" task recursively on a Deno workspace and fix linting issues found.
  entry: deno task --recursive
  args:
    - lint:fix
  language: system
  types:
    - ts
  pass_filenames: false
- id: clang-format-cpp
  name: clang-format (C/C++)
  description: Run clang-format on C/C++ files.
  entry: clang-format --dry-run
  language: system
  types:
    - c
    - c++
- id: clang-format-objc
  name: clang-format (Objective-C)
  description: Run clang-format on Objective-C files.
  entry: clang-format --dry-run
  language: system
  types:
    - objective-c
    - objective-c++
- id: clang-format-java
  name: clang-format (Java)
  description: Run clang-format on Java files.
  entry: clang-format --dry-run
  language: system
  types:
    - java
- id: clang-format-javascript
  name: clang-format (JavaScript)
  description: Run clang-format on JavaScript files.
  entry: clang-format --dry-run
  language: system
  types:
    - javascript
- id: clang-format-csharp
  name: clang-format (C#)
  description: Run clang-format on C# files.
  entry: clang-format --dry-run
  language: system
  types:
    - c#
- id: clang-format-cpp-strict
  name: clang-format (C/C++) (Strict)
  description: Run clang-format on C/C++ files and treat all warnings as errors.
  entry: clang-format --dry-run --Werror
  language: system
  types:
    - c
    - c++
- id: clang-format-objc-strict
  name: clang-format (Objective-C) (Strict)
  description: Run clang-format on Objective-C files  and treat all warnings as errors.
  entry: clang-format --dry-run --Werror
  language: system
  types:
    - objective-c
    - objective-c++
- id: clang-format-java-strict
  name: clang-format (Java) (Strict)
  description: Run clang-format on Java files  and treat all warnings as errors.
  entry: clang-format --dry-run --Werror
  language: system
  types:
    - java
- id: clang-format-javascript-strict
  name: clang-format (JavaScript) (Strict)
  description: Run clang-format on JavaScript files  and treat all warnings as errors.
  entry: clang-format --dry-run --Werror
  language: system
  types:
    - javascript
- id: clang-format-csharp-strict
  name: clang-format (C#) (Strict)
  description: Run clang-format on C# files  and treat all warnings as errors.
  entry: clang-format --dry-run --Werror
  language: system
  types:
    - c#
- id: clang-format-cpp-fix
  name: clang-format (C/C++) (Fix)
  description: Run clang-format on C/C++ files and fix any issues found.
  entry: clang-format -i
  language: system
  types:
    - c
    - c++
- id: clang-format-objc-fix
  name: clang-format (Objective-C) (Fix)
  description: Run clang-format on Objective-C files and fix any issues found.
  entry: clang-format -i
  language: system
  types:
    - objective-c
    - objective-c++
- id: clang-format-java-fix
  name: clang-format (Java) (Fix)
  description: Run clang-format on Java files and fix any issues found.
  entry: clang-format -i
  language: system
  types:
    - java
- id: clang-format-javascript-fix
  name: clang-format (JavaScript) (Fix)
  description: Run clang-format on JavaScript files and fix any issues found.
  entry: clang-format -i
  language: system
  types:
    - javascript
- id: clang-format-csharp-fix
  name: clang-format (C#) (Fix)
  description: Run clang-format on C# files and fix any issues found.
  entry: clang-format -i
  language: system
  types:
    - c#
- id: gradle-spotless
  name: Gradle (Spotless)
  description: Run Spotless via Gradle.
  entry: gradle spotlessCheck
  language: system
  pass_filenames: false
- id: gradle-spotless-fix
  name: Gradle (Spotless) (Fix)
  description: Run Spotless via Gradle and fix any issues found.
  entry: gradle spotlessApply
  language: system
  pass_filenames: false
- id: gradle-spotless-java
  name: Gradle (Spotless) (Java)
  description: Run Spotless via Gradle on Java files.
  entry: gradle spotlessJavaCheck
  language: system
  types:
    - java
  pass_filenames: false
- id: gradle-spotless-java-fix
  name: Gradle (Spotless) (Java) (Fix)
  description: Run Spotless via Gradle on Java files and fix any issues found.
  entry: gradle spotlessJavaApply
  language: system
  types:
    - java
  pass_filenames: false
- id: gradle-spotless-gradle
  name: Gradle (Spotless) (Gradle)
  description: Run Spotless via Gradle on Gradle files.
  entry: gradle spotlessGradleCheck
  language: system
  files: .*\.gradle
  pass_filenames: false
- id: gradle-spotless-gradle-fix
  name: Gradle (Spotless) (Gradle) (Fix)
  description: Run Spotless via Gradle on Gradle files and fix any issues found.
  entry: gradle spotlessGradleApply
  language: system
  files: .*\.gradle
  pass_filenames: false
- id: gradle-spotless-gradle
  name: Gradle (Spotless) (Gradle)
  description: Run Spotless via Gradle on Groovy files.
  entry: gradle spotlessGroovyCheck
  language: system
  types:
    - groovy
  pass_filenames: false
- id: gradle-spotless-groovy-fix
  name: Gradle (Spotless) (Groovy) (Fix)
  description: Run Spotless via Gradle on Groovy files and fix any issues found.
  entry: gradle spotlessGroovyApply
  language: system
  types:
    - groovy
  pass_filenames: false
- id: gradle-spotless-scala
  name: Gradle (Spotless) (Scala)
  description: Run Spotless via Gradle on Scala files.
  entry: gradle spotlessScalaCheck
  language: system
  types:
    - scala
  pass_filenames: false
- id: gradle-spotless-scala-fix
  name: Gradle (Spotless) (Scala) (Fix)
  description: Run Spotless via Gradle on Scala files and fix any issues found.
  entry: gradle spotlessScalaApply
  language: system
  types:
    - scala
  pass_filenames: false
- id: gradle-spotless-kotlin
  name: Gradle (Spotless) (Kotlin)
  description: Run Spotless via Gradle on Kotlin files.
  entry: gradle spotlessKotlinCheck
  language: system
  types:
    - kotlin
  pass_filenames: false
- id: gradle-spotless-kotlin-fix
  name: Gradle (Spotless) (Kotlin) (Fix)
  description: Run Spotless via Gradle on Kotlin files and fix any issues found.
  entry: gradle spotlessKotlinApply
  language: system
  types:
    - kotlin
  pass_filenames: false
- id: gradle-wrapper-spotless
  name: Gradle Wrapper (Spotless)
  description: Run Spotless via the Gradle wrapper.
  entry: ./gradlew spotlessCheck
  language: system
  pass_filenames: false
- id: gradle-wrapper-spotless-fix
  name: Gradle Wrapper (Spotless) (Fix)
  description: Run Spotless via the Gradle wrapper and fix any issues found.
  entry: ./gradlew spotlessApply
  language: system
  pass_filenames: false
- id: gradle-wrapper-spotless-java
  name: Gradle Wrapper (Spotless) (Java)
  description: Run Spotless via the Gradle wrapper on Java files.
  entry: ./gradlew spotlessJavaCheck
  language: system
  types:
    - java
  pass_filenames: false
- id: gradle-wrapper-spotless-java-fix
  name: Gradle Wrapper (Spotless) (Java) (Fix)
  description: Run Spotless via the Gradle wrapper on Java files and fix any issues found.
  entry: ./gradlew spotlessJavaApply
  language: system
  types:
    - java
  pass_filenames: false
- id: gradle-wrapper-spotless-gradle
  name: Gradle Wrapper (Spotless) (Gradle)
  description: Run Spotless via the Gradle wrapper on Gradle files.
  entry: ./gradlew spotlessGradleCheck
  language: system
  files: .*\.gradle
  pass_filenames: false
- id: gradle-wrapper-spotless-gradle-fix
  name: Gradle Wrapper (Spotless) (Gradle) (Fix)
  description: Run Spotless via the Gradle wrapper on Gradle files and fix any issues found.
  entry: ./gradlew spotlessGradleApply
  language: system
  files: .*\.gradle
  pass_filenames: false
- id: gradle-wrapper-spotless-gradle
  name: Gradle Wrapper (Spotless) (Gradle)
  description: Run Spotless via the Gradle wrapper on Groovy files.
  entry: ./gradlew spotlessGroovyCheck
  language: system
  types:
    - groovy
  pass_filenames: false
- id: gradle-wrapper-spotless-groovy-fix
  name: Gradle Wrapper (Spotless) (Groovy) (Fix)
  description: Run Spotless via the Gradle wrapper on Groovy files and fix any issues found.
  entry: ./gradlew spotlessGroovyApply
  language: system
  types:
    - groovy
  pass_filenames: false
- id: gradle-wrapper-spotless-scala
  name: Gradle Wrapper (Spotless) (Scala)
  description: Run Spotless via the Gradle wrapper on Scala files.
  entry: ./gradlew spotlessScalaCheck
  language: system
  types:
    - scala
  pass_filenames: false
- id: gradle-wrapper-spotless-scala-fix
  name: Gradle Wrapper (Spotless) (Scala) (Fix)
  description: Run Spotless via the Gradle wrapper on Scala files and fix any issues found.
  entry: ./gradlew spotlessScalaApply
  language: system
  types:
    - scala
  pass_filenames: false
- id: gradle-wrapper-spotless-kotlin
  name: Gradle Wrapper (Spotless) (Kotlin)
  description: Run Spotless via the Gradle wrapper on Kotlin files.
  entry: ./gradlew spotlessKotlinCheck
  language: system
  types:
    - kotlin
  pass_filenames: false
- id: gradle-wrapper-spotless-kotlin-fix
  name: Gradle Wrapper (Spotless) (Kotlin) (Fix)
  description: Run Spotless via the Gradle wrapper on Kotlin files and fix any issues found.
  entry: ./gradlew spotlessKotlinApply
  language: system
  types:
    - kotlin
  pass_filenames: false
